name=LDRobot-LIDAR-STL
version=0.1.0
author=Phil Schatzmann
maintainer=Phil Schatzmann
sentence=Arduino library for LD LiDAR STL-19P sensor.
paragraph=Parses LiDAR scan packets from serial stream, provides configurable angle and distance unit conversion, with support for result callbacks and debug output.
category=Sensors
url=https://github.com/pschatzmann/LDROBOT-LIDAR-STL.git
architectures=*
